# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(db_column='list', null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
